FROM golang:1.25

WORKDIR /app

RUN apt update && apt install -y \
    git \
    curl \
    vim \
    mpv

RUN go install github.com/go-delve/delve/cmd/dlv@latest

COPY go.mod ./

RUN go mod download

COPY . .

CMD ["bash"]
