FROM golang:1.25

ARG USER_ID=1000
ARG GROUP_ID=1000

RUN groupadd --gid ${GROUP_ID} developer \
    && useradd \
        --uid ${USER_ID} \
        --gid ${GROUP_ID} \
        --create-home \
        --shell /bin/bash \
        developer

WORKDIR /app

RUN apt-get update && apt-get install -y \
    git \
    curl \
    vim \
    mpv \
    pulseaudio-utils \
    unzip

RUN curl -L \
    https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux \
    -o /usr/local/bin/yt-dlp \
    && chmod a+rx /usr/local/bin/yt-dlp

RUN curl -fsSL https://deno.land/install.sh \
    | DENO_INSTALL=/usr/local sh

RUN go install github.com/go-delve/delve/cmd/dlv@latest

COPY go.mod ./

RUN go mod download

COPY . .

CMD ["bash"]
