FROM golang:1.25

ARG USER_ID=1000
ARG GROUP_ID=1000

RUN groupadd --gid ${GROUP_ID} developer \
    && useradd \
        --uid ${USER_ID} \
        --gid ${GROUP_ID} \
        --create-home \
        --shell /bin/bash \
        developer

WORKDIR /app

RUN apt update && apt install -y \
    git \
    curl \
    vim \
    mpv \
    pulseaudio-utils

RUN go install github.com/go-delve/delve/cmd/dlv@latest

COPY go.mod ./

RUN go mod download

COPY . .

CMD ["bash"]
